apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pet-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        # Используем полное имя образа, которое есть в Minikube
        image: 192.168.1.34:8083/pet-project/backend:monitoring-v1
        imagePullPolicy: IfNotPresent  # Будет использовать локальный образ
        ports:
        - containerPort: 5000
        env:
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
